<?php
# Only show partial if data is set
if(array_key_exists('contact_address',$this->aPartialData)) {
    # add address form fields
    $oPrimaryAddress = $this->aPartialData['contact_address']['oPrimaryAddress'];
    $aFields = $this->aPartialData['contact_address']['aFormFields'];
    ?>
    <div class="row">
        <?= $this->partial('partial/basicformfields', ['sFormName' => 'contactaddress-single', 'sTab' => 'address-base', 'aFieldsByTab' => $aFields]); ?>
    </div>
<?php
}
