<?php
use Application\Controller\CoreController;
use OnePlace\Contact\Address\Model\AddressTable;

# Get Form
$oForm = CoreController::$aCoreTables['core-form']->select(['form_key'=>'contactaddress-single']);

# Try to get adress table
try {
    $oAddressTbl = CoreController::$oServiceManager->get(AddressTable::class);
} catch(\RuntimeException $e) {
    echo '<div class="alert alert-danger"><b>Error:</b> Could not load address table</div>';
}

if(isset($oAddressTbl)) {
    # load contact addresses
    $oAddresses = $oAddressTbl->fetchAll(false, ['contact_idfs' => $oItem->getID()]);
    # get primary address
    $oPrimaryAddress = false;
    if (count($oAddresses) > 0) {
        foreach ($oAddresses as $oAddr) {
            $oPrimaryAddress = $oAddr;
            break;
        }
    }
    if (count($oForm) > 0) {
        # add address form fields
        $aFields = [
            'address-base' => CoreController::$aCoreTables['core-form-field']->select(['form' => 'contactaddress-single']),
        ];
        ?>
        <?php if ($oPrimaryAddress) { ?>
            <div class="row">
                <?= $this->partial('partial/viewformfields', ['sFormName' => 'contactaddress-single', 'sTab' => 'address-base', 'oItem' => $oPrimaryAddress, 'aFormFieldsByTab' => $aFields]); ?>
            </div>
        <?php } else { ?>
            <div class="alert alert-info">No Address</div>
        <?php }
    } else {
        echo '<div class="alert alert-danger"><b>Error:</b> Could not load address form</div>';
    }
}
