<?php
# Only show partial if data is set
if(array_key_exists('contact_address',$this->aPartialData)) {
    # add address form fields
    $oPrimaryAddress = $this->aPartialData['contact_address']['oPrimaryAddress'];
    $oAddresses =  $this->aPartialData['contact_address']['oAddresses'];
    $aFields = $this->aPartialData['contact_address']['aFormFields'];
    ?>
    <?php if ($oPrimaryAddress) { ?>
        <input type="hidden" name="contactaddress-single_address_primary_id" value="<?=$oPrimaryAddress->getID()?>" />
        <div class="row">
            <?= $this->partial('partial/basicformfields', ['sFormName' => 'contactaddress-single', 'sTab' => 'address-base', 'oItem' => $oPrimaryAddress, 'aFieldsByTab' => $aFields]); ?>
        </div>
    <?php } else { ?>
        <div class="row">
            <?= $this->partial('partial/basicformfields', ['sFormName' => 'contactaddress-single', 'sTab' => 'address-base', 'aFieldsByTab' => $aFields]); ?>
        </div>
    <?php }
}
