<?php
# Only show partial if data is set
if(array_key_exists('contact_address',$this->aPartialData)) {
    # add address form fields
    $oPrimaryAddress = $this->aPartialData['contact_address']['oPrimaryAddress'];
    $aFields = $this->aPartialData['contact_address']['aFormFields'];
    ?>
    <?php if ($oPrimaryAddress) { ?>
        <div class="row">
            <?= $this->partial('partial/viewformfields', ['sFormName' => 'contactaddress-single', 'sTab' => 'address-base', 'oItem' => $oPrimaryAddress, 'aFormFieldsByTab' => $aFields]); ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-info">No Address</div>
    <?php }
}
